// <auto-generated />
namespace CoffeeStore.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class setRestOfData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setRestOfData));
        
        string IMigrationMetadata.Id
        {
            get { return "202403311416317_setRestOfData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
